spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://db:3306/petmily?serverTimezone=Asia/Seoul
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  admin: isadmin

jwt:
  secret: HADEN
  admin:  isadmin

oauth2:
  kakao:
    client-id: 
  naver:
    client-id: 
    client-secret: 
  google:
    client-id: 
    client-secret: 

