spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
  jap:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  admin: isadmin

jwt:
  secret: HADEN
  admin:  isadmin
